### ISSUE TITLE
Karmabot can't parse dashes

### ISSUE THREAD

**Issue by blkperl** [chromakode/karmabot#1]
00:38 < blkperl> karmabot: ruby-debug is like gdb but shiny
00:38 < karmabot> Huh?

**Comment by miller-time** [comment]
try (ruby-debug) for now. thanks, i'll keep that in mind when working on this parser

**Comment by blkperl** [comment]
yea i did that but when you ask it ruby-debug later it doesn't associate the value unless it has the parens

**Comment by miller-time** [comment]
yeah it reads it as 2 separate strings
